# Generated by Django 4.2.13 on 2024-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_payments_payment_payments_payment_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_status",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="статус платежа"
            ),
        ),
    ]
